FORMAT: 1A
HOST: https://sandbox.bitwala.io/api/v1

# Bitwala API v1

Welcome to the Bitwala API documentation. At Bitwala we get the chance to work with partners from all corners of the ecosystem and this is one of the most rewarding parts of the job. These docs are to help you get up and running as quickly as possible. We’re very excited to see what you build.

## Additional Resources
* [Slack channel](https://slack.bitwala.io)
* [Node client](https://github.com/bitwala/api-node-client)
* Sample Application TODO

## Communicating with us
* Technical issues - Chat with us in slack
* Customer support issues - [support@bitwala.io](mailto:support@bitwala.io)

## What you can do
This version of the API is limited to the **bank transfer** functionality of bitwala.

* Get info about Bitwala’s payment services
* Create bank transfers
* Manage bank transfers

## Versioning
We follow a major.minor versioning scheme. Having `/v1` in your path indicates you are using the version 1.x of the api. All 1.x versions will be backwards compatible with previous 1.x versions.

## Changelog
| Version                            | Date Released | Changes         |
|------------------------------------|------------|-----------------|
| v1.0                               | 2017-05-19 | Initial version |


## Environments
There is a sandbox environment and a production environment.

|                                       | Sandbox                           | Production                   |
|---------------------------------------|-----------------------------------|------------------------------|
| Endpoint                              | https://sandbox.bitwala.io/api/v1 | https://my.bitwala.io/api/v1 |
| Mainnet BTC                           | Yes                               | Yes                          |
| Bitwala admins need to approve access | No                                | Yes                          |
| Can simulate payment via web GUI?     | Yes                               | No                           |

## Ratelimiting
API calls are limited to 10 requests per token per second.

# Implementation Choices

We tend to follow the [JSON API conventions](http://jsonapi.org/format/).

## Headers
All requests must be sent with `content-type: application/vnd.api+json`.

## Response format

### Successful responses
* 200 / 201 status code
* Top level `data` key with primary data
* Top level `status` key with value `"success"`

TODO add example

### Error responses
* 4xx error codes
* Top level `status` key with value `"error"`
* Top level `error` key with an error key

TODO add example

| What happened                 | HTTP Status code | Key                         |
|-------------------------------|------------------|-----------------------------|
| Cannot find token             | 404              | token-not-found             |
| App not authorised by Bitwala | 403              | bitwala-admin-auth-required |
| Missing permissions           | 403              | missing-permissions         |
| Missing Headers               | 400              | missing-headers             |
| Bad nonce                     | 403              | nonce-invalid               |
| Content Type wrong            | 400              | bad-content-type            |
| Signature is invalid          | 403              | signature-invalid           |
| Route not found               | 404              | not-found                   |

## Webhooks
Webhooks have a similar format to successful responses, containing a `status: ‘success’` key and a data key. 
`data` key holds the updated version of the transaction.

There are two ways to validate:
1. Check the `x-bitwala-signature` is valid (webhook requests are signed in the same way as api requests)
2. Make an API call to retrieve up to date data

Webhooks are considered successful if they receive a 2xx status. Webhooks are repeated in increasing time intervals while they are not successful. This happens a finite number of times.

| Attempt # | Interval   |
|-----------|------------|
| 1         | 1 second   |
| 2         | 5 seconds  |
| 3         | 15 seconds |
| 4         | 1 minute   |
| 5         | 2 minutes  |
| 6         | 5 minutes  |
| 7         | 30 minutes |
| 8         | 1 hour     |
| 9         | 4 hour     |
| 10        | 12 hour    |
| 11        | 24 hours   |

A webhook is triggered when:
  * a transaction input's status has updated;
  * a transaction output's status has updated;
  * transaction was marked as having a problem; 
  * transaction had a problem and the problem was resolved;


# Authentication
There are 2 ways to use the Bitwala API. Not sure which one is right for you? Get in touch.

## 1. Internal use
### Use cases
* A startup paying fiat salaries, using Bitcoin to fund these payments
* An ICO backed company liquidating crypto into company’s bank account

### KYC
**The organisation needs to be KYC’d.**

Once you sign up and your organisation is verified, you can make api calls using a **single token**.

## 2. Customer Use
### Use cases
* A wallet giving customers the option to cash out their bitcoins from within the app
* An app enabling 2 or more parties to split a bill with bitcoin

### KYC
**Each customer needs to be KYC’d.**

We need to know about each customer. They must create a Bitwala account and go through the regular verification steps. Users give partners permission to act on their behalf. An individual authenticates the app and **a different token must be used for each user.**

## KYC via contract
Do you have high levels of KYC? In a few cases, we can sign a contract with you, guaranteeing that you will do the KYC to our standards and make it available on request. The advantage is a simpler authentication flow. Please get in touch.

## Authentication flow
### Internal use
1. Go to (sanbox.)bitwala.io/api-apps
2. Create an app and select “Internal use”
3. Generate a token (id and secret) and store both securely.

### Customer use
#### Initial set up 
1. Go to (sanbox.)bitwala.io/api-apps
2. Create an app and select “Customer use”
3. Customise your app with relevant information that your customers will see e.g. logo
4. Make a note of your app ID

#### Creating a token and having the user authenticate it
1. In your app, prompt your users to authenticate via a popup or webview*
2. The user will be prompted with a screen asking them to accept your permissions. They will be redirected  to the same url with the success=true or false parameter before the window / webview attempts to close itself
3. Either via detecting a change in the iframe/webview url or testing via the `/auth` endpoint it’s possible to know whether the user authenticated

*The url must match the following pattern `https://bitwala/authenticate/:appId?permissions=BANKTRANSFERS.CREATE,BANKTRANSFER.READ` where the permissions parameter is a comma separated list of permissions.
 
 
Note: Users can revoke permissions at any time via the web GUI

## Headers
In either case, the security headers are the same.

The headers:
* x-bitwala-token - the id of the token
* x-bitwala-signature - data from request signed by the secret of the token
* x-bitwala-nonce - a number that must always be bigger than the last nonce used

### x-bitwala-token
The ID of the token provided at the time of its creation.

Example: `WcjGxNg93BQzPEXrh`

### x-bitwala-nonce
This is a number that is higher than the last nonce used. This is to prevent replay attacks.

Best practise is to use a linux timestamp.

Range: 0 - 4102444800000

Example: `1495712605839`

### x-bitwala-signature
The signature is produced from the token secret, x-bitwala-nonce and the request and is a hex-string representation of the result of the following hash calculation:

`HMAC-SHA512(secret, msg)`

Where:

`secret` is the API token secret,

`msg` is a utf-8 string, constructed by concatenating request URI path, hexdigest of the request data and nonce:

`msg = uri_path + SHA256(request_data) + nonce`

`uri_path` is the path of the URI e.g. `/api/v1/transactions`

`nonce` is the `x-bitwala-nonce` included as a header

The `SHA256(request_data)` is a SHA256 digest of the `request_data`.

The request data is either
* For POST requests: the JSON encoded request body
* For GET requests: the URL encoded query

#### Example 1 (signing a POST request)
Your API token id is `WcjGxNg93BQzPEXrh`

Your API token secret is `KsmBR7ny1Xj7sQR5FemteMEKATIr7kGUn9/dQnuM7EKBagyX5HNLdt+Uj92+Uihd`

You are making a POST request to `/api/v1/transactions/cancel`, the nonce is `1495712605839` and the POST request body is `{"transactionId":"DqDfZBbhFHXXhMXB33K"}`

`uri_path` is then `/api/v1/transactions/cancel`

In such case `request_data` is the JSON encoded POST request body, i.e. string `{"transactionId":"DqDfZBbhFHXXhMXB33K"}`

`msg` is then `/api/v1/transactions/cancel9c99258e64d38a652600b46fff5f7951a2663095501b4fd60b237d69b8ce5a2d1495712605839`

`x-bitwala-signature` is then `25093dc010099ad8240aedf96129d622dd082e10df7d3a272e48ce0abe6a645cf99fe38895c390f182110d8a31867058281db597f82c79b96c8d1028adc58d6c`

#### Example 2 (signing a GET request)
Your API token id is `WcjGxNg93BQzPEXrh`

Your API token secret is `KsmBR7ny1Xj7sQR5FemteMEKATIr7kGUn9/dQnuM7EKBagyX5HNLdt+Uj92+Uihd`

You are making a GET request to `/api/v1/transactions?page=1`, the nonce is `1495712605839`

`uri_path` is then `/api/v1/transactions?page=1`

In such case `request_data` is the URL encoded query, i.e. string `page=1`

`msg` is then `/api/v1/transactions?page=1c5c34f0fdf091a49d75cc51b4f64ab34cbae49cf4914bb0a0a1c0c599b7a43731495712605839`

`x-bitwala-signature` is then `afe76be769c02ced85542c41ca15632d673bf9c708b584731a500c5062a778ab7a2af3edddd8c12994a5ebc2c204f3e5d11ad2612846659bd6a12fb84d95c402`

#### Example 3 (verifying a webhook signature)
You received a webhook - a POST request with the following headers:

`x-bitwala-token`: `WcjGxNg93BQzPEXrh` - this is the id of the API token, which was used to create this webhook.

`x-bitwala-nonce`: `1495712605839`

`x-bitwala-signature`: `103efa9353aed4beffab87abf0f9869b8f839119c8a042e9f8f1621f4d0aa2c42368a7fd6ac5ec2b9590300b7dbf768273e1d72b967dcbc07adb935840abb6c7`


The secret of the API token with id `WcjGxNg93BQzPEXrh` is `KsmBR7ny1Xj7sQR5FemteMEKATIr7kGUn9/dQnuM7EKBagyX5HNLdt+Uj92+Uihd`

To verify a webhook you can calculate its expected signature in the same way as in example 1 and compare the result with the `x-bitwala-signature` header:

The URL, where you received the webhook is `https://my.webhookurl.com` - this is the `uri_path`

The webhook POST request body is `{"status":"success","data":"some_data"}` - this is the `request_data`

`nonce` is the `x-bitwala-nonce` header

`msg` is then `https://my.webhookurl.com54b5d3f1d8a7680754ae1c5214afd3b50f1ed0b194ec345d8223649e753f87921495712605839`

And the right signature in this case really is `103efa9353aed4beffab87abf0f9869b8f839119c8a042e9f8f1621f4d0aa2c42368a7fd6ac5ec2b9590300b7dbf768273e1d72b967dcbc07adb935840abb6c7`


If you are able to, using the [node client](https://github.com/bitwala/api-node-client) will take care of this for you. Want to write your own client? Please get in touch.

### Testing
You can check that your authenticating correctly by GETting the `/auth` endpoint.

# Group Info 
## Status [/info]
### Get status [GET]
Call to check that the API is working.

`issues` describes distruptions to our service.
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                "apiStatus": "running",
                "issues": {
                    "open": [],
                    "lastTwoWeeks": [
                        {
                            "_id": "TdSXjTxo7LLRY497p",
                            "title": "Bank Holiday",
                            "description": "Bank Transfers will not be made on this Monday due to a bank holiday in Germany.",
                            "incidentType": "Information",
                            "status": "Resolved",
                            "createdAt": "2017-05-17T17:21:10.469Z",
                            "resolvedAt": "2017-05-17T17:21:10.470Z"
                        }
                    ]
                }
            }
        }

## Inputs [/info/inputs]
### List inputs [GET]
Inputs are ways to pay into Bitwala e.g. a Bitcoin Invoice.
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "collection": "BitcoinInvoices",
                        "currency": "XBT"
                    }
                ]
            }
        }
        
## Outputs [/info/outputs]
### Get outputs [GET]
Outputs are possible payment ways that Bitwala can pay out e.g. a EUR bank transfer.
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "bankTransfers": [
                            {
                                "value": "EUR",
                                "label": "EUR",
                                "symbol": "€",
                                "countryIso": "EUROPEANUNION",
                                "countryDescription": "SEPA zone",
                                "eta": {
                                    "express": {
                                        "unit": "sameBusinessDay"
                                    },
                                    "standard": {
                                        "unit": "days",
                                        "from": 1
                                    }
                                },
                                "requiredVerificationLevel": 0,
                                "bankSchema": "1"
                            },
                            {
                                "value": "GBP",
                                "label": "GBP",
                                "symbol": "£",
                                "countryIso": "GB",
                                "countryDescription": "United Kingdom",
                                "eta": {
                                    "express": {
                                        "unit": "days",
                                        "from": 1,
                                        "to": 3
                                    },
                                    "standard": {
                                        "unit": "days",
                                        "from": 2,
                                        "to": 4
                                    }
                                },
                                "requiredVerificationLevel": 0,
                                "bankSchema": "2"
                            },
                            ...
                        ]
                    }
                ]
            }
        }

# Group Auth
## Auth [/auth]
### Check authentication [GET]
Check that authentication method is valid.

**Customer Use** partners can get info about permissions.
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                "app": {
                    "_id": "mEXPhNZxaZQycfn8E",
                    "scope": "INTERNAL",
                    "enabled": true,
                    "name": "My wonderful app"
                },
                "token": {
                    "createdAt": "2017-05-16T13:32:53.689Z"
                }
            }
        }


# Group Transactions
Transactions have the format:
```
{
    "_id": "3mzuZ6Pf7DEpuT8Ro",
    "createdAt": ISODate("2017-01-24T07:20:59.884Z"),
    "problem": false,
    "problemStatus": "",
    "isCanceled": false,
    "ref": "your_internal_tx_id",
    "webhookUrl": "https://your.webhookurl.com",
    "inputsStatus": "confirmed",
    "outputsStatus": "pending",
    "refundStatus": "",
    "inputs": [{
        "collection": "BitcoinInvoices",
        "doc": {
            "_id": "rfKx7BnBrCKHqD3",
            "createdAt": ISODate("2017-01-24T07:20:59.884Z"),
            "status": "confirmed",
            "convertedCurrency": "EUR",
            "currency": "XBT",
            "fee": 0.5,
            "convertedAmount": 100,
            "validUntil": ISODate("2016-10-26T12:05:16.217Z"),
            "total": 0.166225
            "depositAddress": "1FyWCZnxVeJRVdgCHaDLu5SzMwHuSUtY5a"
        }
    }],
    "outputs": [{
        "collection": "BankTransfers",
        "doc": {
            "_id": "heO73mSDx1z21MtM2",
            "createdAt": ISODate("2017-01-24T07:20:59.884Z"),
            "status": "pending",
            "amount": 100,
            "currency": "EUR",
            "reference": "May Salary",
            "bankAccount": {
                "recipientType": "INDIVIDUAL",
                "firstName": "Satoshi",
                "lastName": "Nakamoto",
                "iban": "DE89370400440532013000",
                "currency": "EUR"
            }
            
        }
    }]
}
```
### Inputs and outputs
The `inputs` and `outputs` fields are an array of objects with two keys, `collection` and `doc`.

Inputs are ways that money enters Bitwala. Outputs are ways that money leaves.

A typical transfer has a `BitcoinInvoices` doc as the input and a `BankTransfers` doc as an output. This is the only pair currently supported by the API.

* Inputs convert from the `currency` to the `convertedCurrency`
* The sum of the `convertedAmount`'s of the inputs must be equal to the sum of `amount`'s of the `outputs`
* The `convertedCurrency` of the inputs must be the same as the `currency` of the outputs
* A `fee` denominated in the `convertedCurrency` is added on each of the inputs

### Statuses and flow
Inputs and outputs have a `status` field that can take one of three values: `new`, `pending`, `confirmed`.

#### Inputs
* `new` created - payment is required.
* `pending` payment received, but not confirmed yet (e.g. waiting for X bitcoin confirmations)
* `confirmed` payment confirmed

#### Outputs
* `new` created
* `pending` ready to be executed e.g. waiting for admin
* `confirmed` payment sent out

#### Typical payment flow
A typical payment flow with a bitcoin invoice and bank transfer goes through the following steps:

1. Transaction created - `inputs` and `outputs` have `new` status, transaction's `inputsStatus` and `outputsStatus` fields are both `new`
2. Correct Bitcoin payment received for a particular input - the input changes from `new` to `pending`
3. The payment confirms X times - the input changes from `pending` to `confirmed`
4. When all the inputs become `pending` transaction's `inputsStatus` becomes `pending`
5. This triggers transaction's `outputsStatus` and the outputs' statuses to change from `new` to `pending`
6. The admin makes a bank transfer for every output and updates the output's status to `confirmed`
7. When all the outputs become `confirmed` transaction's `outputsStatus` becomes `confirmed`

A webhook is triggered every time status of a transaction's input or output changes. 

If an input's or output's status change has triggered the change of either `inputsStatus` or `outputsStatus` of the transaction, the webhook body will have these fields properly updated.

#### Problem status
The payment flow is interrupted whenever `problem` is `true` on the transaction object.

Typical cases for a problem status:
* Bitcoin payment after an invoice has exprired
* Underpayment of a bitcoin invoice
* Bank transfer rejected by the recipient bank

In the event of `problem` being set to `true`, `problemStatus` will be set to a string describing the problem.

Problems must be resolved by contacting the Bitwala admin via [support@bitwala.io](mailto:support@bitwala.io).

When a transaction's `problem` field changes, a webhook will be sent.

### Other fields
#### Transaction
* `ref` is a custom ref, e.g. an ID from your own business logic
* `refundStatus` exists when a refund has been processed on a tx
* `isCanceled` is `true` when the tx has been canceled
* `problemStatus` gives a description of the problem with the tx
* `webhookUrl`, if provided, is a url where webhooks for this transaction are going to be sent

#### BankTransfers
* `paidAt` is the time when the bank transfer was made
* `reference` is the refence that will be sent with the bank transfer

### Multiple inputs / outputs
It's possible to have multiple inputs or outputs e.g. splitting a payment into multiple bitcoin invoices or making multiple bank transfers with one bitcoin invoice.

## List transactions [/transactions?page={page}]
### List transactions by page [GET]
Get a list of transactions, ordered by the most recent. Limited to 50. Paginated
+ Parameters
    + page (number) - Non-zero postive integer
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                "status": "ok"
            }
        }


## Get a single transaction by transactionId [/transactions?transactionId={transactionId}]        
### Get a transaction by transactionId [GET]
+ Parameters
    + transactionId (string) - ID of transaction
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                "status": "ok"
            }
        }

## Get a single transaction by ref [/transactions?ref={ref}]        
### Get a transaction by ref [GET]
+ Parameters
    + ref (string) - ref specified at time of transaction creation
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                "status": "ok"
            }
        }

## Create a transaction [/transactions]
### Create a transaction [POST]
### Correctly formatting the bank account
Different currencies require different bank schemas.

| ISO | Bank Schema |
|-----|-------------|
| EUR | 1           |
| GBP | 2           |
| USD | 2           |
| SEK | 2           |
| HUF | 2           |
| NOK | 2           |
| HRK | 2           |
| CHF | 2           |
| CZK | 2           |
| DKK | 2           |
| PLN | 2           |

#### Common fields
Bank schemas must contain
* `currency` which is the capitalised 3 letter [currency iso](https://en.wikipedia.org/wiki/ISO_4217)
* `recipientType` which must be `INDIVIDUAL` or `ORGANISATION`
* If `INDIVIDUAL`, `firstName` and `lastName` must be supplied
* If `ORGAGNISATION`, `organisationName` must be supplied

#### Bank Schema 1 (EUR)
Additionally fields:
* `iban` - the iban of the bank account

Example:
```
{
    "bankAccount": {
        "recipientType": "INDIVIDUAL",
        "firstName": "Satoshi",
        "lastName": "Nakamoto",
        "currency": "EUR"
        "iban": "DE89370400440532013000",
        
    }
}
```

#### Bank Schema 2 (Other currencies)
Additionally fields:
* `accountNumber` is the IBAN or account number of the bank
* `bic` is the [BIC code](https://en.wikipedia.org/wiki/ISO_9362)
* `recipientAddress` is address of the recipient
* `recipientCountry` is the capitalised [2 letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the recipient
* `bankName` is the name of the recipient bank
* `bankAddress` is the address of the recipient bank
* `bankCountry` is the capitalised [2 letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the bank

Example: 
```
{
    "bankAccount": {
        "recipientType": "ORGANISATION",
        "organisationName": "Satoshi Ltd.",
        "accountNumber": "GB29NWBK60161331926819",
        "bic": "MIDLGB22",
        "recipientAddress": "1 Holborn, London",
        "recipientCountry": "GB",
        "bankName": "HSBC",
        "bankAddress": "1 Chancery Lane, London",
        "bankCountry": "GB"
    }
}
```


+ Request (application/vnd.api+json)

        {
            "ref": "My custom id",
            "inputs": [
                "collection": "BitcoinInvoices",
                "doc": {
                    "currency": "XBT"
                    "convertedCurrency": "EUR",
                    "convertedAmount": 100
                }
            ],
            "outputs": [
                "collection": "BankTransfers",
                "doc": {
                    "amount": 100,
                    "currency": "EUR",
                    "reference": "January Salary",
                    "bankAccount": {
                        "recipientType": "INDIVIDUAL",
                        "firstName": "Satoshi",
                        "lastName": "Nakamoto",
                        "iban": "DE89370400440532013000",
                        "currency": "EUR"
                    }
                }
            ]
        }
+ Response 201 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                {
                  "_id": "3mzuZ6Pf7DEpuT8Ro",
                  "createdAt": ISODate("2017-01-24T07:20:59.884Z"),
                  "problem": false,
                  "problemStatus": "",
                  "isCanceled": false,
                  "ref": "My custom id",
                  "inputsStatus": "new",
                  "outputsStatus": "new",
                  "refundStatus": "",
                  "inputs": [{
                      "collection": "BitcoinInvoices",
                      "doc": {
                          "_id": "rfKx7BnBrCKHqD3",
                          "createdAt": ISODate("2017-01-24T07:20:59.884Z"),
                          "status": "new",
                          "convertedCurrency": "EUR",
                          "currency": "XBT",
                          "fee": 0.5,
                          "convertedAmount": 100,
                          "validUntil": ISODate("2016-10-26T12:05:16.217Z"),
                          "total": 0.166225
                          "depositAddress": "1FyWCZnxVeJRVdgCHaDLu5SzMwHuSUtY5a"
                      }
                  }],
                  "outputs": [{
                      "collection": "BankTransfers",
                      "doc": {
                          "_id": "heO73mSDx1z21MtM2",
                          "createdAt": ISODate("2017-01-24T07:20:5984Z"),
                          "status": "pending",
                          "amount": 100,
                          "currency": "EUR",
                          "reference": "January Salary",
                          "bankAccount": {
                              "recipientType": "INDIVIDUAL",
                              "firstName": "Satoshi",
                              "lastName": "Nakamoto",
                              "iban": "DE89370400440532013000",
                              "currency": "EUR"
                          }
            
                      }
                  }]
              }
            }
        }

## Cancel a transaction [/transactions/cancel]
It is possible to cancel a not yet paid transaction.

If the transaction has at least one input with not `new` status, an error will be thrown. If you need to cancel such transaction, please, contact support.

Trying to cancel an already canceled transaction will produce an error.
### Cancel a transaction [POST]
+ Request (application/vnd.api+json)

        {
           "transactionId": "3mzuZ6Pf7DEpuT8Ro"
        }
+ Response 200 (application/vnd.api+json)

        {
            "status": "success",
            "data": {
                "canceled": "3mzuZ6Pf7DEpuT8Ro"
            }
        }

## Refresh transaction inputs [/transactions/refresh]
Refreshing transaction inputs means getting new bitcoin invoices for the same transaction. Useful if e.g. an invoice has expired.

`invoices` is an optional field, if it's not provided all transaction inputs will be updated, i.e. replaced with new invoices.
Specifying `invoices` might be useful to update only particular inputs for a transaction with multiple inputs.

Successful response contains the updated transaction with new inputs for the same currency and amount.

Trying to update a paid invoice (i.e. an invoice with not `new` status), as well as trying to update input for a canceled transaction, will produce an error.
### Refresh transaction inputs [POST]
+ Request (application/vnd.api+json)

        {
           "transactionId": "3mzuZ6Pf7DEpuT8Ro",
           "invoices": [ "n94t56qLHR7RCeyZW", "JzdSTYx9ZqMDYmbTr" ]
        }
+ Response 200 (application/vnd.api+json)

        {
          "status": "success",
          "data": {
            "_id": "3mzuZ6Pf7DEpuT8Ro",
            "ref": "1232342qq",
            "createdAt": "2017-05-23T12:59:46.008Z",
            "updatedAt": "2017-05-23T16:04:06.144Z",
            "inputsStatus": "new",
            "outputsStatus": "new",
            "isCanceled": false,
            "problem": false,
            "inputs": [
              {
                "_id": "bTFXqivmXW7tHbH98",
                "currency": "XBT",
                "convertedCurrency": "EUR",
                "convertedAmount": 200,
                "fee": 1,
                "status": "new",
                "problem": false,
                "convertedTotal": 201,
                "depositAddress": "1KFrC4WAR2swxVzYhynont4ficakooAczc",
                "createdAt": "2017-05-23T16:04:06.123Z",
                "updatedAt": "2017-05-23T16:04:06.133Z"
              },
              {
                "_id": "ZLAocTusK8iyu9KNG",
                "currency": "XBT",
                "convertedCurrency": "EUR",
                "convertedAmount": 100,
                "fee": 1,
                "status": "new",
                "problem": false,
                "convertedTotal": 101,
                "depositAddress": "1KFrC4WAR2swxVzYhynont4ficakooAczc",
                "createdAt": "2017-05-23T16:04:06.123Z",
                "updatedAt": "2017-05-23T16:04:06.133Z"
              }
            ],
            "outputs": [
              {
                "_id": "ckYiQsD2dxN4gGrLN",
                "amount": 300,
                "currency": "EUR",
                "reference": "May salary",
                "bankAccount": {
                  "recipientType": "INDIVIDUAL",
                  "firstName": "Satoshi",
                  "lastName": "Nakamoto",
                  "iban": "DE89370400440532013000",
                  "currency": "EUR",
                  "obfuscatedIban": "DE89xxxxxxxxxxxxxxxxx"
                },
                "createdAt": "2017-05-23T12:59:45.989Z",
                "updatedAt": "2017-05-23T12:59:45.989Z",
                "status": "new",
                "problem": false
              }
            ]
          }
        }